language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: JLXmxdi6e4bnvy4KIVK48m9L0dhXX7X/LALx0Y2u+TjsK1ouMk7QgmIIcThsrx7+95FGr8dbCf/XM4vybIw8++iSxdEsxuUZHrnATfnm9sRXMgTvk6VVovEAIy64MloY90IM1TyBgt6Q/8nEu9MIWt/RwPnIC6xLctAv5DGDSVM9TytYhowwW/DlWfb5i1w4yfSTu6ejQyRpHFVRxcbRsEn2iMeWx/51jFOD28aw7cOMsFV+kjQCi1aymI3eVZRgJ3+aE0Fm4KU94yeN4ygaLxv4ucg5QK1LLLmHu+6h5d72bvrDbT00DEoVqIMa4dlLO1gA8xqRv4JrxzpC5xgRLOsL18QRq1VvmuyXcArcY/UVpLxT/Vic0NDbtQ/mt4Ad8OSogTKB0Ul7RIUhbiW407b7HkOmqJW+rNm96gXD4awkP2Id1VYy80BVXgKEeBJJtgwgwp95qZUnAQTk5wiygNba1A+4Ctmxv7HwBzTMYy9tJoUjrgByl0SMAS21T+LYY4NI19ZcMEBZvaCYXvBitfYveJCoO19isUD3cclrU6TzGz28g+UfQ50luGOU5CgaU4/wBJqS0ryxVSJHmU6xjkExAVU9rvljLXBFh8E7jr9kgVPFjnUNk1QxM70wDgWEBq0NH+AtmdAQ7ECKvmbO7adlLd8t3VrDGZs2SCr4UBo=
  - secure: Mq0X9Xb9/9CenjtpNeIEf1S3IpcC7lxIxDsKf7+1UYa1VVsdFxlJVP+SxAGEjxIKKfufseFclOo0UITw2F+tYQvx7L1VgDFq35/JSrGhCOGVcw7wCeeHo/YqeI1t9dH3eDhprvtfPXIwd24IMeUG9jy0/U55VSABy+qLnByDawmOp6Wiu601I4dmCpHmXkTZuMRsNMBuyo6lFlsm2GoCQTrIR+KRsBMSxn+PaZf4rHHnHOk7PpHa1bS7oc+k92VbVEHVUwxr+1jjx84qApWrvez8fgBeEqlaDrYclJSIaEtj71zwJG8SfIGDBZii2joi4+WNTc5BlU1K/AE+WycOB9Mp4bkaNIqdmcy/0bHue8C8/4DTDe/3KYIEPy7GFzi+mzuv1lSTl9OV2l49iTxE1rtjC1ptKR+QfyzWBFc7Kml8QId0AZxHtQGzpM9/yUdRFCocYDjztU0SimTunM99mpD4/xkQgWob99lSNh8U+9B4gaRZvmwlCc5UMrJU0hU/koxU5VZ1TJlUtPnXzDUnLGzWPIJ33YY9/vJi0NR20camI2g6zFNtno/5R2qE0P0f43zj3LeR9DPr/qFdipxf7ODwaDJfQpgIK2CrEG9+FUzkwkpmULLLVScQc2c58xnpwhNSwVcKKvuCrmeJO7OL+KKskSMIrclU5UXget5RYek=
